package com.example.franc.fitnessshop.Interface;

import android.view.View;

/**
 * Created by franc on 22/11/2017.
 */

//Interface used to click items generated by the FirebaseRecyclerAdapter
public interface WelcomeClickListener {
    void onClick(View v, int selection, boolean longClick);
}
